import { useAuth } from "../hooks/useAuth";
import Head from "next/head";
import styles from "../styles/Home.module.scss";
import Post from "../components/Post/Post";
import PostForm from "../components/PostForm/PostForm";
import Bio from "../components/Bio/Bio";
import { logOut } from "../lib/auth";

export default function Home() {
	const { user, logIn, logOut } = useAuth();
	console.log("user", user);

	return (
		<div className={styles.container}>
			<Head>
				<title>My Posts</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			{!user && (
				<p>
					<button onClick={logIn}>Log In</button>
				</p>
			)}

			{user && (
				<p>
					<button onClick={logOut}>Log Out</button>
				</p>
			)}

			<main className={styles.main}>
				<Bio
					headshot="https://pbs.twimg.com/profile_images/924397205246525440/JL7gtm8Y_400x400.jpg"
					name="Ayush Adarsh"
					tagLine="Watching & Learning...🙂"
					role="Automation Engineer @ Publicis Sapient"
				/>
				<ul className={styles.posts}>
					<li>
						<Post
							content="Figma desigining tool to display the tweets
							om my application"
							date="November 21, 2021"
						/>
					</li>
					<li>
						<Post
							content="Figma desigining tool to display the tweets
							om my application"
							date="November 21, 2021"
						/>
					</li>
					<li>
						<Post
							content="Figma desigining tool to display the tweets
							om my application"
							date="November 21, 2021"
						/>
					</li>
					<li>
						<Post
							content="Figma desigining tool to display the tweets
							om my application"
							date="November 21, 2021"
						/>
					</li>
				</ul>

				{user && <PostForm />}
			</main>
		</div>
	);
}
