import { useEffect, useState } from "react";
import { useAuth } from "../hooks/useAuth";
import Head from "next/head";
import styles from "../styles/Home.module.scss";
import Post from "../components/Post/Post";
import PostForm from "../components/PostForm/PostForm";
import Bio from "../components/Bio/Bio";
import { logOut } from "../lib/auth";

export default function Home({ posts: defaultPosts }) {
	const { user, logIn, logOut } = useAuth();
	const [posts, updatePosts] = useState(defaultPosts);

	useEffect(() => {
		async function run() {
			const response = await fetch(
				`${process.env.NEXT_PUBLIC_API_ENDPOINT}/api/posts`,
			);
			const { posts } = await response.json();
			updatePosts(posts);
		}
	}, []);

	return (
		<div className={styles.container}>
			<Head>
				<title>My Posts</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			{!user && (
				<p>
					<button onClick={logIn}>Log In</button>
				</p>
			)}

			{user && (
				<p>
					<button onClick={logOut}>Log Out</button>
				</p>
			)}

			<main className={styles.main}>
				<Bio
					headshot="https://pbs.twimg.com/profile_images/924397205246525440/JL7gtm8Y_400x400.jpg"
					name="Ayush Adarsh"
					tagLine="Watching & Learning...🙂"
					role="Automation Engineer @ Publicis Sapient"
				/>
				<ul className={styles.posts}>
					{posts.map((post) => {
						const { content, date, id } = post;
						return (
							<li key={id}>
								<Post
									content={content}
									date={new Intl.DateTimeFormat(
										"en-US",
										{
											dateStyle:
												"full",
											timeStyle:
												"short",
										},
									).format(new Date(date))}
								/>
							</li>
						);
					})}
				</ul>

				{user && <PostForm />}
			</main>
		</div>
	);
}

export async function getStaticProps() {
	const response = await fetch(`${process.env.NEXT_PUBLIC_API_ENDPOINT}/api/posts`);
	const { posts } = await response.json();

	return {
		props: {
			posts,
		},
	};
}
